SxTree::LexerStruct::Structure::LexerStructPos Struct Reference
#include <LexerStructPos.h>
Public Member Functions
LexerStructPos (const string *s)
decltype(LexerStructPos::storage->end()) end () const
decltype(LexerStructPos::storage->begin()) begin () const
size_t getPosNow () const
const string * getStorage () const
void moveForward (unsigned long dist)
void moveBack (unsigned long dist)
bool isEnded () const
Data Fields
size_t posNow
const string * storage
Detailed Description
Constructor & Destructor Documentation
LexerStructPos()
SxTree::LexerStruct::Structure::LexerStructPos::LexerStructPos (const string * s) [explicit]
: posNow(0), storage(s) {}
Member Function Documentation
begin()
decltype(LexerStructPos::storage->begin()) SxTree::LexerStruct::Structure::LexerStructPos::begin () const
Referenced by SxTree::LexerStruct::LexerStruct::pValue().
end()
decltype(LexerStructPos::storage->end()) SxTree::LexerStruct::Structure::LexerStructPos::end () const
Referenced by SxTree::LexerStruct::LexerStruct::pValue().
getPosNow()
size_t SxTree::LexerStruct::Structure::LexerStructPos::getPosNow () const
                                           {
        return posNow;
    }
References posNow.
getStorage()
const string * SxTree::LexerStruct::Structure::LexerStructPos::getStorage () const
                                                   {
        return storage;
    }
References storage.
isEnded()
bool SxTree::LexerStruct::Structure::LexerStructPos::isEnded () const
                                       {
        return posNow >= storage->size();
    }
References posNow, and storage.
Referenced by SxTree::Lexer::Lexer::parse().
moveBack()
void SxTree::LexerStruct::Structure::LexerStructPos::moveBack (unsigned long dist)
                                                    {
        posNow -= dist;
    }
References posNow.
Referenced by SxTree::LexerStruct::LexerStruct::expectWord().
moveForward()
void SxTree::LexerStruct::Structure::LexerStructPos::moveForward (unsigned long dist)
                                                       {
        posNow += dist;
    }
References posNow.
Referenced by SxTree::LexerStruct::LexerStruct::expectWord(), SxTree::LexerStruct::LexerStruct::pRule(), SxTree::LexerStruct::LexerStruct::pValue(), and SxTree::LexerStruct::LexerStruct::skipChars().
Field Documentation
posNow
size_t SxTree::LexerStruct::Structure::LexerStructPos::posNow
Referenced by SxTree::Lexer::Lexer::addError(), SxTree::LexerStruct::LexerStruct::expectClosingBracket(), SxTree::LexerStruct::LexerStruct::getChar(), getPosNow(), isEnded(), moveBack(), moveForward(), SxTree::Lexer::Lexer::parse(), SxTree::LexerStruct::LexerStruct::parseRules(), SxTree::LexerStruct::LexerStruct::pExpression(), SxTree::LexerStruct::LexerStruct::pRule(), and SxTree::LexerStruct::LexerStruct::pValue().
storage
const string* SxTree::LexerStruct::Structure::LexerStructPos::storage
Referenced by SxTree::LexerStruct::LexerStruct::getChar(), getStorage(), isEnded(), and SxTree::Lexer::Lexer::parse().
The documentation for this struct was generated from the following files:
/Users/alexroar/Desktop/Dev/SxTree/include/Lexer/LexerStructPos.h
/Users/alexroar/Desktop/Dev/SxTree/src/Lexer/LexerStructPos.cpp