SxTree::Lexer::Lexeme Class Reference
#include <Lexeme.h>
Public Member Functions
Lexeme (const Lexeme &other)
Lexeme (Lexeme &&other) noexcept
Lexeme (const string *sourceText, unsigned lexType, size_t startInd, size_t lexSize) noexcept
Lexeme (const Lexeme &first, const Lexeme &second, unsigned lexType) noexcept
Lexeme (const Lexeme &first, const Lexeme &second) noexcept
void connect (const Lexeme &other, unsigned newType) noexcept
void operator+= (const Lexeme &other) noexcept
Lexeme operator+ (const Lexeme &other) const noexcept
bool operator== (const Lexeme &other) const noexcept
void setType (unsigned pString) noexcept
string to_string () const
string valueString () const
unsigned getType () const
size_t getStart () const
size_t getSize () const
Static Public Member Functions
static Lexeme zero ()
Private Member Functions
void leftConnect (const Lexeme &other, unsigned newType) noexcept
void rightConnect (const Lexeme &other, unsigned newType) noexcept
Private Attributes
const string * source
unsigned type
size_t start
size_t size
Detailed Description
Constructor & Destructor Documentation
Lexeme() [1/5]
SxTree::Lexer::Lexeme::Lexeme (const Lexeme & other) [default]
Referenced by zero().
Lexeme() [2/5]
SxTree::Lexer::Lexeme::Lexeme (Lexeme && other) [noexcept]
                                         :
            source(other.source),
            type(other.type),
            start(other.start),
            size(other.size){
        other.type = 0;
        other.source = nullptr;
        other.start = other.size = 0;
    }
Lexeme() [3/5]
SxTree::Lexer::Lexeme::Lexeme (const string * sourceText, unsigned lexType, size_t startInd, size_t lexSize) [noexcept]
                                                                                                      :
            source(sourceText),
            type(lexType),
            start(startInd),
            size(lexSize){
    }
Lexeme() [4/5]
SxTree::Lexer::Lexeme::Lexeme (const Lexeme & first, const Lexeme & second, unsigned lexType) [noexcept]
                                                                                       :
            source(first.source),
            type(first.type),
            start(first.start),
            size(first.size){
        connect(second, lexType);
    }
Lexeme() [5/5]
SxTree::Lexer::Lexeme::Lexeme (const Lexeme & first, const Lexeme & second) [noexcept]
Warning
Lexemes must have the same type
Parameters
first
second
                                                                    :
            source(first.source),
            type(first.type),
            start(first.start),
            size(first.size){
        assert(first.type == second.type);
        connect(second, second.type);
    }
Member Function Documentation
connect()
void SxTree::Lexer::Lexeme::connect (const Lexeme & other, unsigned newType) [noexcept]
Connects the lexeme to the current one
Parameters
other
newType
                                                                       {
        if (other.size == 0) {
            type = newType;
            return;
        }
        if (other.start < start)
            leftConnect(other, newType);
        else
            rightConnect(other, newType);
    }
Referenced by SxTree::LexerStruct::Structure::Expression::exprParseOneType().
getSize()
size_t SxTree::Lexer::Lexeme::getSize () const
                                 {
        return size;
    }
References size.
getStart()
size_t SxTree::Lexer::Lexeme::getStart () const
                                                   {
        return start;
    }
References start.
getType()
unsigned SxTree::Lexer::Lexeme::getType () const
                                   {
        return type;
    }
References type.
leftConnect()
void SxTree::Lexer::Lexeme::leftConnect (const Lexeme & other, unsigned newType) [private], [noexcept]
Merge two lexemes by appending other lexeme other + this
Parameters
other
newType
                                                                           {
        assert((other.start + other.size <= start) && "Invalid lexemes placement");
        const size_t margin = start - (other.start + other.size);
        start = other.start;
        size += other.size + margin;
        type = newType;
    }
operator+()
Lexeme SxTree::Lexer::Lexeme::operator+ (const Lexeme & other) const [noexcept]
Connects lexemes
Warning
Lexemes must have the same type
Parameters
other
                                                               {
        assert(type == other.type);
        return Lexeme(*this, other);
    }
operator+=()
void SxTree::Lexer::Lexeme::operator+= (const Lexeme & other) [noexcept]
Connects the lexeme to the current one
Warning
Lexemes must have the same type
Parameters
other
                                                        {
        assert(type == other.type);
        connect(other, other.type);
    }
operator==()
bool SxTree::Lexer::Lexeme::operator== (const Lexeme & other) const [noexcept]
Warning
Sources are compared by the pointers, not values
Parameters
other
Returns
                                                              {
        if (other.size == size && size == 0)
            return true;
        if (!type || !source || other.type || other.source)
            return false;
        return other.start == start && other.size == size && type == other.type && source == other.source;
    }
rightConnect()
void SxTree::Lexer::Lexeme::rightConnect (const Lexeme & other, unsigned newType) [private], [noexcept]
Merge two lexemes by appending other lexeme this + other
Parameters
other
newType
                                                                            {
        assert((other.start >= start + size) && "Invalid lexemes placement");
        const size_t margin = other.start - (size + start);
        size += other.size + margin;
        type = newType;
    }
setType()
void SxTree::Lexer::Lexeme::setType (unsigned pString) [noexcept]
Update lexeme type
Parameters
pString
                                                 {
        type = pString;
    }
to_string()
string SxTree::Lexer::Lexeme::to_string () const
Standard to_string function
Returns
string representation
                                   {
        std::stringstream ss;
        ss << "Lexeme<id=" << type << ", start=" << start << ", size=" << (size) << ">";
        return ss.str();
    }
References size, start, and type.
valueString()
string SxTree::Lexer::Lexeme::valueString () const
Retrieve text of this lexeme from the source text
Returns
                                    {
        assert(source && "Source can't be nullptr");
        return source->substr(start, size);
    }
References size, source, and start.
zero()
Lexeme SxTree::Lexer::Lexeme::zero () [static]
Create zero lexeme – zero size, zero position
Returns
                        {
        return Lexeme(nullptr, 0, 0, 0);
    }
References Lexeme().
Referenced by SxTree::Lexer::Lexer::parse(), SxTree::LexerStruct::Structure::Expression::parse(), and SxTree::LexerStruct::Structure::Expression::parseSkipping().
Field Documentation
size
size_t SxTree::Lexer::Lexeme::size [private]
Size of lexeme in the source
Referenced by getSize(), to_string(), and valueString().
source
const string* SxTree::Lexer::Lexeme::source [private]
Source text where this lexeme located
Referenced by valueString().
start
size_t SxTree::Lexer::Lexeme::start [private]
Start position of lexeme in the source
Referenced by getStart(), to_string(), and valueString().
type
unsigned SxTree::Lexer::Lexeme::type [private]
The type of lexeme
Referenced by getType(), and to_string().
The documentation for this class was generated from the following files:
/Users/alexroar/Desktop/Dev/SxTree/include/Lexer/Lexeme.h
/Users/alexroar/Desktop/Dev/SxTree/src/Lexer/Lexeme.cpp