SxTree::LexerStruct::LexerStruct Class Reference
#include <LexerStruct.h>
Public Member Functions
LexerStruct () noexcept
void parseRules (const string &storage) noexcept
decltype(LexerStruct::errors) const & getErrors ()
const vector< Structure::Rule > & getRules () const
const unordered_map< string, unsigned > & getLexemesMap () const
Private Member Functions
unsigned getRuleId (const string &id)
optional< Rule > pRule (LexerStructPos &lexerStructPos)
optional< Expression > pExpression (LexerStructPos &lexerStructPos)
optional< Value > pValue (LexerStructPos &lexerStructPos)
void skipChars (LexerStructPos &lexerStructPos, const std::set< char > &chars)
bool expectWord (LexerStructPos &lexerStructPos, const char *word)
optional< Expression > expectClosingBracket (LexerStructPos &lexerStructPos, Expression &expr)
Static Private Member Functions
static bool isEnded (LexerStructPos &lexerStructPos) noexcept
static char getChar (LexerStructPos &lexerStructPos)
Private Attributes
unordered_map< string, unsigned > ruleIdsNo
vector< Structure::Rule > rules
vector< Structure::ParseError > errors
Detailed Description
Constructor & Destructor Documentation
LexerStruct()
SxTree::LexerStruct::LexerStruct::LexerStruct () [default], [noexcept]
Member Function Documentation
expectClosingBracket()
optional< Expression > SxTree::LexerStruct::LexerStruct::expectClosingBracket (LexerStructPos & lexerStructPos, Expression & expr) [private]
                                                                                                            {
        switch (expr.type) {
            case Expression::EXP_ONE: {
                if (!expectWord(lexerStructPos, ")")) {
                    errors.push_back({"Expected ')' after expression", lexerStructPos.posNow});
                    skipChars(lexerStructPos, skipBefore);
                    return std::__1::optional<Expression>();
                }
                break;
            }
            case Expression::EXP_ANY: {
                if (!expectWord(lexerStructPos, "]")) {
                    errors.push_back({"Expected ']' after expression", lexerStructPos.posNow});
                    skipChars(lexerStructPos, skipBefore);
                    return std::__1::optional<Expression>();
                }
                break;
            }
            case Expression::EXP_OPTIONAL: {
                if (!expectWord(lexerStructPos, "]")) {
                    errors.push_back({"Expected ']' after ?[ expression", lexerStructPos.posNow});
                    skipChars(lexerStructPos, skipBefore);
                    return std::__1::optional<Expression>();
                }
                break;
            }
        }
        return std::__1::optional<Expression>(std::move(expr));
    }
References errors, SxTree::LexerStruct::Structure::Expression::EXP_ANY, SxTree::LexerStruct::Structure::Expression::EXP_ONE, SxTree::LexerStruct::Structure::Expression::EXP_OPTIONAL, expectWord(), SxTree::LexerStruct::Structure::LexerStructPos::posNow, SxTree::LexerStruct::skipBefore, skipChars(), and SxTree::LexerStruct::Structure::Expression::type.
Referenced by pExpression().
expectWord()
bool SxTree::LexerStruct::LexerStruct::expectWord (LexerStructPos & lexerStructPos, const char * word) [private]
                                                                                 {
        assert(word && "Cannot expect nullptr string");
        unsigned i = 0;
        while (*word) {
            if (getChar(lexerStructPos) != *word) {
                lexerStructPos.moveBack(i);
                return false;
            }
            word++;
            i++;
            lexerStructPos.moveForward(1);
        }
        return true;
    }
References getChar(), SxTree::LexerStruct::Structure::LexerStructPos::moveBack(), and SxTree::LexerStruct::Structure::LexerStructPos::moveForward().
Referenced by expectClosingBracket(), pExpression(), pRule(), and pValue().
getChar()
char SxTree::LexerStruct::LexerStruct::getChar (LexerStructPos & lexerStructPos) [static], [private]
                                                            {
        return (*lexerStructPos.storage)[lexerStructPos.posNow];
    }
References SxTree::LexerStruct::Structure::LexerStructPos::posNow, and SxTree::LexerStruct::Structure::LexerStructPos::storage.
Referenced by expectWord(), pRule(), and skipChars().
getErrors()
decltype(LexerStruct::errors) const& SxTree::LexerStruct::LexerStruct::getErrors ()
Referenced by main().
getLexemesMap()
const unordered_map< string, unsigned > & SxTree::LexerStruct::LexerStruct::getLexemesMap () const
                                                                            {
        return ruleIdsNo;
    }
References ruleIdsNo.
getRuleId()
unsigned SxTree::LexerStruct::LexerStruct::getRuleId (const string & id) [private]
                                                    {
        const auto found = ruleIdsNo.find(id);
        if (found == ruleIdsNo.end()) {
            ruleIdsNo[id] = ruleIdsNo.size();
            return ruleIdsNo.size() - 1;
        }
        return found->second;
    }
References ruleIdsNo.
Referenced by pRule().
getRules()
const vector< Structure::Rule > & SxTree::LexerStruct::LexerStruct::getRules () const
                                                             {
        return rules;
    }
References rules.
isEnded()
bool SxTree::LexerStruct::LexerStruct::isEnded (LexerStructPos & lexerStructPos) [static], [private], [noexcept]
                                                                     {
        return lexerStructPos.isEnded();
    }
Referenced by skipChars().
parseRules()
void SxTree::LexerStruct::LexerStruct::parseRules (const string & storage) [noexcept]
                                                               {
        LexerStructPos lexerStructPos(&storage);
        while (errors.empty() && !isEnded(lexerStructPos)) {
            auto rule = pRule(lexerStructPos);
            if (rule.has_value()) {
                rules.push_back(std::move(rule.value()));
            } else {
                skipChars(lexerStructPos, skipBefore);
                if (!isEnded(lexerStructPos))
                    errors.push_back({"Invalid rule", lexerStructPos.posNow});
                break;
            }
            skipChars(lexerStructPos, skipBefore);
        }
    }
References SxTree::LexerStruct::Structure::LexerStructPos::posNow, and SxTree::LexerStruct::skipBefore.
Referenced by main().
pExpression()
optional< Expression > SxTree::LexerStruct::LexerStruct::pExpression (LexerStructPos & lexerStructPos) [private]
                                                                                {
        skipChars(lexerStructPos, skipLine);
        Expression::ExprType type = Structure::Expression::EXP_ONE;
        if (!expectWord(lexerStructPos, "(")) {
            if (!expectWord(lexerStructPos, "[")) {
                if (!expectWord(lexerStructPos, "?[")) {
                    errors.push_back({"Expected left parenthesis before expression", lexerStructPos.posNow});
                    skipChars(lexerStructPos, skipBefore);
                    return optional<Expression>();
                } else
                    type = Structure::Expression::EXP_OPTIONAL;
            } else
                type = Structure::Expression::EXP_ANY;
        }
        skipChars(lexerStructPos, skipLine);
        auto firstExpr = pValue(lexerStructPos);
        if (!firstExpr.has_value()) {
            errors.push_back({"At least one rule required in the expression", lexerStructPos.posNow});
            return optional<Expression>();
        }
        Expression expr;
        expr.type = type;
        expr.possible.push_back(std::move(firstExpr.value()));
        while (true) {
            skipChars(lexerStructPos, skipLine);
            if (expectWord(lexerStructPos, ",")) {
                skipChars(lexerStructPos, skipLine);
                auto nextExpr = pValue(lexerStructPos);
                if (!nextExpr.has_value()) {
                    errors.push_back({"Expected a comma before declarations", lexerStructPos.posNow});
                    skipChars(lexerStructPos, skipBefore);
                    return optional<Expression>();
                }
                expr.possible.push_back(std::move(nextExpr.value()));
            } else
                break;
        }
        return expectClosingBracket(lexerStructPos, expr);
    }
References errors, SxTree::LexerStruct::Structure::Expression::EXP_ANY, SxTree::LexerStruct::Structure::Expression::EXP_ONE, SxTree::LexerStruct::Structure::Expression::EXP_OPTIONAL, expectClosingBracket(), expectWord(), SxTree::LexerStruct::Structure::LexerStructPos::posNow, SxTree::LexerStruct::Structure::Expression::possible, pValue(), SxTree::LexerStruct::skipBefore, skipChars(), SxTree::LexerStruct::skipLine, and SxTree::LexerStruct::Structure::Expression::type.
Referenced by pRule(), and pValue().
pRule()
optional< Rule > SxTree::LexerStruct::LexerStruct::pRule (LexerStructPos & lexerStructPos) [private]
                                                                    {
        skipChars(lexerStructPos, skipBefore);
        string id;
        char tmpChar = 0;
        while (isalpha(tmpChar = getChar(lexerStructPos)) || isdigit(tmpChar)) {
            id += tmpChar;
            lexerStructPos.moveForward(1);
        }
        skipChars(lexerStructPos, skipLine);
        if (!expectWord(lexerStructPos, "=")) {
            errors.push_back({"No '=' symbol after identifier", lexerStructPos.posNow});
            skipChars(lexerStructPos, skipBefore);
            return optional<Rule>();
        }
        skipChars(lexerStructPos, skipLine);
        auto expr = pExpression(lexerStructPos);
        if (!expr.has_value()) {
            errors.push_back({"Invalid expression after <id> = ", lexerStructPos.posNow});
            skipChars(lexerStructPos, skipBefore);
            return optional<Rule>();
        }
        skipChars(lexerStructPos, skipLine);
        if (!expectWord(lexerStructPos, "\n")) {
            errors.push_back({"No new line after definition", lexerStructPos.posNow});
            skipChars(lexerStructPos, skipBefore);
            return optional<Rule>();
        }
        return optional<Rule>({getRuleId(id), expr.value()});
    }
References errors, expectWord(), getChar(), getRuleId(), SxTree::LexerStruct::Structure::LexerStructPos::moveForward(), pExpression(), SxTree::LexerStruct::Structure::LexerStructPos::posNow, SxTree::LexerStruct::skipBefore, skipChars(), and SxTree::LexerStruct::skipLine.
pValue()
optional< Value > SxTree::LexerStruct::LexerStruct::pValue (LexerStructPos & lexerStructPos) [private]
                                                                      {
        auto getExpr = [=](LexerStructPos &lexerStructPos, const char *errMsg, bool skip=false) -> optional<Value> {
            auto expr = pExpression(lexerStructPos);
            if (!expr.has_value()) {
                errors.push_back({errMsg, lexerStructPos.posNow});
                return optional<Value>();
            }
            return Value(expr.value(), skip);
        };
        skipChars(lexerStructPos, skipLine);
        if (expectWord(lexerStructPos, "skip"))
            return getExpr(lexerStructPos, "Expected expression directly after 'skip' keyword", true);
        std::regex rgx(R"((["'])(?:(?=(\\?))\2.)*?\1)");
        std::sregex_iterator current(lexerStructPos.begin(), lexerStructPos.end(), rgx);
        std::sregex_iterator end;
// printf("%s\n", current->str().c_str());
        if (current == end || current->position() != 0)
            return getExpr(lexerStructPos, "Malformed rule");
        if (current->str().size() <= 2) {
            errors.push_back({"RegExpr can't be empty", lexerStructPos.posNow});
            return optional<Value>();
        }
        string stringReg = current->str();/*std::regex_replace(current->str(), std::regex(R"(\\")"), "\"");*/
        stringReg = stringReg.substr(1, current->str().size() - 2);
        lexerStructPos.moveForward(current->str().size());
        try {
            return Value(stringReg);
        } catch (const std::regex_error &e) {
            errors.push_back({"Wrong regular expression detected", lexerStructPos.posNow});
            errors.push_back({e.what(), lexerStructPos.posNow});
            return optional<Value>();
        }
    }
References SxTree::LexerStruct::Structure::LexerStructPos::begin(), SxTree::LexerStruct::Structure::LexerStructPos::end(), errors, expectWord(), SxTree::LexerStruct::Structure::LexerStructPos::moveForward(), pExpression(), SxTree::LexerStruct::Structure::LexerStructPos::posNow, skipChars(), and SxTree::LexerStruct::skipLine.
Referenced by pExpression().
skipChars()
void SxTree::LexerStruct::LexerStruct::skipChars (LexerStructPos & lexerStructPos, const std::set< char > & chars) [private]
                                                                                         {
        while (!isEnded(lexerStructPos)) {
            if (chars.find(getChar(lexerStructPos)) != chars.end())
                lexerStructPos.moveForward(1);
            else
                break;
        }
    }
References getChar(), isEnded(), and SxTree::LexerStruct::Structure::LexerStructPos::moveForward().
Referenced by expectClosingBracket(), pExpression(), pRule(), and pValue().
Field Documentation
errors
vector<Structure::ParseError> SxTree::LexerStruct::LexerStruct::errors [private]
Referenced by expectClosingBracket(), pExpression(), pRule(), and pValue().
ruleIdsNo
unordered_map<string, unsigned> SxTree::LexerStruct::LexerStruct::ruleIdsNo [private]
Referenced by getLexemesMap(), and getRuleId().
rules
vector<Structure::Rule> SxTree::LexerStruct::LexerStruct::rules [private]
Referenced by getRules().
The documentation for this class was generated from the following files:
/Users/alexroar/Desktop/Dev/SxTree/include/Lexer/LexerStruct.h
/Users/alexroar/Desktop/Dev/SxTree/src/Lexer/LexerStruct.cpp