SxTree::LexerStruct::Structure::Expression Struct Reference
#include <StructureUnits.h>
Public Types
enum ExprType { EXP_ONE
, EXP_ANY
, EXP_OPTIONAL
 }
Public Member Functions
optional< Lexeme > parse (LexerStructPos &lexer) const noexcept
optional< Lexeme > parseSkipping (LexerStructPos &lexer) const noexcept
Expression ()
Expression (vector< Value > possibleNew, ExprType typeNew)
optional< Lexeme > exprParseOneType (LexerStructPos &lexer) const
optional< Lexeme > exprParseAnyType (LexerStructPos &lexer) const
Data Fields
vector< Value > possible
ExprType type
Detailed Description
Member Enumeration Documentation
ExprType
enum SxTree::LexerStruct::Structure::Expression::ExprType
Enumerator
EXP_ONE
EXP_ANY
EXP_OPTIONAL
                      {
            EXP_ONE,
            EXP_ANY,
            EXP_OPTIONAL
        };
Constructor & Destructor Documentation
Expression() [1/2]
SxTree::LexerStruct::Expression::Expression ()
: type(EXP_ONE) {}
Expression() [2/2]
SxTree::LexerStruct::Expression::Expression (std::vector< Value > possibleNew, ExprType typeNew)
                                                                         :possible(std::move(possibleNew)), type(typeNew) {
    }
Member Function Documentation
exprParseAnyType()
optional< Lexeme > SxTree::LexerStruct::Structure::Expression::exprParseAnyType (LexerStructPos & lexer) const
                                                                                       {
        for (const auto & val : possible) {
            auto tryParse = val.parse(lexer);
            if (tryParse.has_value()) {
// lexer.moveForward(tryParse.value().getSize());
                return tryParse.value();
            }
        }
        return optional<Lexeme>();
    }
exprParseOneType()
optional< Lexeme > SxTree::LexerStruct::Structure::Expression::exprParseOneType (LexerStructPos & lexer) const
                                                                                       {
        auto firstLexeme = possible[0].parse(lexer);
        if (!firstLexeme.has_value())
            return optional<Lexeme>();
        Lexeme &lexeme = firstLexeme.value();
        for (auto val = ++(possible.begin()); val != possible.end(); ++val) {
            auto tryParse = val->parse(lexer);
            if (!tryParse.has_value())
                return optional<Lexeme>();
            lexeme.connect(tryParse.value(), tmpLexType);
        }
        return optional<Lexeme>(std::move(lexeme));
    }
References SxTree::Lexer::Lexeme::connect(), and SxTree::LexerStruct::tmpLexType.
parse()
optional< Lexeme > SxTree::LexerStruct::Structure::Expression::parse (LexerStructPos & lexer) const [noexcept]
                                                                                    {
        assert((!possible.empty()) && "Can't have empty rules");
        switch (type) {
            case EXP_ONE:
                return exprParseOneType(lexer);
            case EXP_ANY:
                return exprParseAnyType(lexer);
            case EXP_OPTIONAL: {
                auto parsed = exprParseAnyType(lexer);
                if (parsed.has_value())
                    return parsed;
                return Lexeme::zero();
            }
        }
    }
References SxTree::Lexer::Lexeme::zero().
parseSkipping()
optional< Lexeme > SxTree::LexerStruct::Structure::Expression::parseSkipping (LexerStructPos & lexer) const [noexcept]
                                                                                            {
        assert((!possible.empty()) && "Can't have empty rules");
        bool found = false;
        for (const auto &val : possible)
            found |= val.parse(lexer).has_value();
        if (!found)
            return std::optional<Lexeme>();
        return std::optional<Lexeme>(Lexeme::zero());
    }
References SxTree::Lexer::Lexeme::zero().
Field Documentation
possible
vector<Value> SxTree::LexerStruct::Structure::Expression::possible
Referenced by SxTree::LexerStruct::LexerStruct::pExpression().
type
ExprType SxTree::LexerStruct::Structure::Expression::type
Referenced by SxTree::LexerStruct::LexerStruct::expectClosingBracket(), and SxTree::LexerStruct::LexerStruct::pExpression().
The documentation for this struct was generated from the following files:
/Users/alexroar/Desktop/Dev/SxTree/include/Lexer/StructureUnits.h
/Users/alexroar/Desktop/Dev/SxTree/src/Lexer/StructureUnits.cpp