SxTree::Lexer::Lexer Class Reference
#include <Lexer.h>
Public Member Functions
Lexer (const vector< Rule > &rulesNew)
vector< Lexeme > parse (const string &parseContent)
const vector< LexerError > & getErrors () const
Private Member Functions
void addError (const char *msg)
Private Attributes
string content
LexerStructPos lexPos
vector< Rule > rules
vector< LexerError > errors
Detailed Description
Constructor & Destructor Documentation
Lexer()
SxTree::Lexer::Lexer::Lexer (const vector< Rule > & rulesNew) [explicit]
                                             :
            lexPos(nullptr),
            rules(rulesNew){}
Member Function Documentation
addError()
void SxTree::Lexer::Lexer::addError (const char * msg) [private]
                                        {
        errors.push_back({msg, lexPos.posNow});
    }
References errors, lexPos, and SxTree::LexerStruct::Structure::LexerStructPos::posNow.
Referenced by parse().
getErrors()
const vector< LexerError > & SxTree::Lexer::Lexer::getErrors () const
                                                     {
        return errors;
    }
References errors.
parse()
vector< Lexeme > SxTree::Lexer::Lexer::parse (const string & parseContent)
                                                          {
        vector<Lexeme> lexemes;
        content = parseContent;
        lexPos.storage = &content;
        lexPos.posNow = 0;
        while (!lexPos.isEnded()) {
            bool resolved = false;
            for (const auto& rule: rules) {
                auto lexeme = rule.parse(lexPos);
                if (lexeme.has_value()){
                    resolved = true;
                    if(lexeme.value() != Lexeme::zero())
                        lexemes.push_back(std::move(lexeme.value()));
                    break;
                }
            }
            if (!resolved) {
                addError("Unresolved sequence");
                break;
            }
        }
        return lexemes;
    }
References addError(), content, SxTree::LexerStruct::Structure::LexerStructPos::isEnded(), lexPos, SxTree::LexerStruct::Structure::LexerStructPos::posNow, rules, SxTree::LexerStruct::Structure::LexerStructPos::storage, and SxTree::Lexer::Lexeme::zero().
Field Documentation
content
string SxTree::Lexer::Lexer::content [private]
Referenced by parse().
errors
vector<LexerError> SxTree::Lexer::Lexer::errors [private]
Referenced by addError(), and getErrors().
lexPos
LexerStructPos SxTree::Lexer::Lexer::lexPos [private]
Referenced by addError(), and parse().
rules
vector<Rule> SxTree::Lexer::Lexer::rules [private]
Referenced by parse().
The documentation for this class was generated from the following files:
/Users/alexroar/Desktop/Dev/SxTree/include/Lexer/Lexer.h
/Users/alexroar/Desktop/Dev/SxTree/src/Lexer/Lexer.cpp